name: Code Review on Push

on:
  push:
    branches:
      - main

jobs:
  code-review:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Code Review
        uses: M0ch0/gemini-code-review-action-full-context@0.1.5
        with:
                  
          gemini_api_key: ${{ secrets.GEMINI_API_KEY }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          github_repository: ${{ github.repository }}
          
          # default is text-davinci-003
          model: "gemini-1.5-pro"
          # Extra prompt for GPT
          extra_prompt: |-
            escreva as revisões de tendo como base os princípios da engenharia de software
